{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3)==5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntestcases\\test_inc.py:5: AssertionError"}, "start": 1586517621600, "stop": 1586517621600, "uuid": "106855d1-27ef-4bae-8951-6f39962bf362", "historyId": "009eb7e016b5546642a9f80ac231fbe7", "testCaseId": "8a8207b8c71415199ce71304892d8ebe", "fullName": "testcases.test_inc#test_answer", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_inc"}, {"name": "host", "value": "DESKTOP-938U3RR"}, {"name": "thread", "value": "1168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_inc"}]}