{"uuid": "38f01426-23d5-4152-b012-0c106808e6af", "children": ["b65892f4-2ae8-4383-b479-d5fd89457ca5", "bc6eb210-3244-4d8b-b65d-ac08e3ca2c30", "db0ee9e6-39f0-42bf-9664-6cb6ae71cf1e", "c1e3886f-ec86-47cd-bec6-75728d505221", "53f8ccab-8cfc-46f2-89c6-c24f86fa69ad", "09f8de1f-9409-410c-9671-59d84c6eec01", "33e69fe6-c1ca-4de1-b9d0-627e4e40cabe", "f6975d7c-fd7c-41d0-b829-d9fa32ef84ee", "8024568a-8980-45fa-9e1c-815da1830120", "e6974401-a9b9-4409-9826-8b223f7ed067", "18e1e9fb-a1d0-42a0-b0a6-4c452cc45778", "0a8f383a-0041-48c3-a924-2c86631d777d"], "befores": [{"name": "session_fixtrue", "status": "broken", "statusDetails": {"message": "TypeError: request() got an unexpected keyword argument 'date'\n", "trace": "  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\PyCharm\\PycharmProjects\\requests\\conftest.py\", line 19, in session_fixtrue\n    resp=http.post(path,date)\n  File \"D:\\PyCharm\\PycharmProjects\\requests\\util\\httpUtil.py\", line 14, in post\n    resp=self.http.post(url,date=date_json)\n  File \"C:\\Users\\GuoBiaoBiao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 578, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n"}, "start": 1586522122067, "stop": 1586522122067}], "start": 1586522122067, "stop": 1586522122505}