{"name": "test_login_fail", "status": "broken", "statusDetails": {"message": "KeyError: 'date3'", "trace": "@pytest.fixture(scope='session',autouse=True)\n    def session_fixtrue10():\n        path='/api/learning/v3/judge'\n>       date=date1[\"date3\"]\nE       KeyError: 'date3'\n\nconftest.py:80: KeyError"}, "start": 1586522703397, "stop": 1586522703397, "uuid": "23161abe-e692-4198-b29c-068035e9c646", "historyId": "faaf16db42328d14a17b9143c87594f2", "testCaseId": "4d2fd9c86f5ffb069562c8495780fca5", "fullName": "testcases.test_login.Test_login#test_login_fail", "labels": [{"name": "feature", "value": "登录成功"}, {"name": "story", "value": "登录失败"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-938U3RR"}, {"name": "thread", "value": "4472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}